mrjones2014/smart-splits.nvim

lua/smart-resize/init.lua

Removed `print(vim.inspect(amount))` from the plugin. This was causing the plugin to print out the value a user sets for their resize amount.
1. Pull this branch
2. install the changes with packer
3. Confirm that the plugin is no longer echoing out the value set for amount.
```lua
use({
"hsheikhali1/smart-resize.nvim",
branch = "remove-debug-lines",
config = function()
local amount = 4
require('smart-resize').resize_up(amount)
require('smart-resize').resize_down(amount)
require('smart-resize').resize_left(amount)
require('smart-resize').resize_right(amount)
end
})
```
It shouldn't echo out the line numbers specified.

Remove debug line outputting amount set for resizing

---

lua/smart-splits/tmux.lua

check tmux session before attempting to change tmux panes

---

README.md
lua/smart-splits/api.lua
lua/smart-splits/config.lua
lua/smart-splits/tmux.lua

add option to disable tmux navigation when zoomed

---

lua/smart-splits/config.lua

`$TMUX` will return a value if it's running on your system, even if it's not in the active pane/emulator. `$TERM_PROGRAM` will be more accurate to the instance running.
To reproduce issue:
1. In any terminal emulator, run tmux
2. Run WezTerm and neovim
3. Use plugin commands. Plugin silently fails because it thinks it should be running tmux commands, not WezTerm commands.

fix(mux): Use `$TERM_PROGRAM` in multiplexer detection

---

lua/smart-splits/api.lua
lua/smart-splits/mux/init.lua
lua/smart-splits/mux/kitty.lua
lua/smart-splits/mux/tmux.lua
lua/smart-splits/mux/wezterm.lua
lua/smart-splits/types.lua

Hi, thanks for a great plugin :) 
There is just a small one thing that I am missing - ability to resize multiplexer windows from the neovim window when there are no splits. This PR adds support for that. 
I don't know much about kitty nor wezterm, so for now I put there some notification that this operation is not supported.

feat(mux): Resize with multiplexer when only single window in `tmux`

---

lua/smart-splits/api.lua

Previously the size calculation hardcoded subtracting 1 for the statusline.
But this is not correct, if the user sets `laststatus=0` for example.
Fix this by respecting the `laststatus` setting in the size calculation.
This problem was found in https://github.com/vimpostor/vim-tpipeline/issues/55

fix: Respect hidden statusline in window size calculation

---

README.md

The `adjust-pane-size` subcommand of `wezterm cli` is currently only available in nightly versions, [as explained here](https://wezfurlong.org/wezterm/cli/cli/adjust-pane-size.html). This commit adds a note in the readme with this info. (this commit should be reverted after the subcommand is available in stable builds)

docs: add note about wezterm integration

---

lua/smart-splits/mux/tmux.lua

fix(mux): fix edge pane detection logic for tmux (#118)

---

lua/smart-splits/commands.lua

Add commands for buffer swap.
I eventually settle for `SmartSwapLeft/Down/Up/Right` for the command names.
Fixes #137 .

fix: Add missing buffer swap commands

---

README.md
plugin/init.lua

Fixes #143 
Note: this functionality is still experimental.

feat(mux): Add Wezterm plugin for easier setup on Wezterm (experimental)

---

lua/smart-splits/api.lua

error detail:
```
E5108: Error executing lua ...are/nvim/lazy/smart-splits.nvim/lua/smart-splits/api.lua:472: E11: Invalid in command-line window; <CR> executes, CTRL-C quits
stack traceback:
[C]: in function 'nvim_set_current_win'
...are/nvim/lazy/smart-splits.nvim/lua/smart-splits/api.lua:472: in function 'resize_up'
[string ":lua"]:1: in main chunk
```
Steps to repro:
1. `q:` to open cmd win.
2. try to resize the cmd win.

fix: E5108 error in command line buffer

---

README.md

In the documentation examples for `ignored_buftypes` and `ingored_filetypes` were inverted.

docs: correct ignored buftypes and filetypes usage

---

README.md
autoload/smart_splits.vim
flake.lock
flake.nix
lua/smart-splits/config.lua
lua/smart-splits/mux/init.lua
lua/smart-splits/mux/tmux.lua
lua/smart-splits/mux/utils.lua
lua/smart-splits/mux/wezterm.lua
lua/smart-splits/types.lua
lua/smart-splits/utils.lua
plugin/smart-splits.lua
plugin/smart-splits.vim

This PR also adds a hook system for multiplexer integrations to run initialization and cleanup functions. `mux.on_init()` is called on startup and `VimResume` while `mux.on_exit()` is called on `VimSuspend` and `VimLeave`.
@b0o would you mind giving this a test for me? It has been a long time since I've used tmux and I don't have a configuration for it at the moment.
1. Use the modified tmux configuration in the README.md changes of this PR
2. Use tmux
3. Ensure `smart-splits.nvim` either auto-detects or is set to use tmux
4. Create multiple tmux splits
5. Open Neovim in one of them and ensure `smart-splits.nvim` is loaded
For me:

feat(mux): Improved tmux integration performance

---

lua/smart-splits/config.lua
lua/smart-splits/mux/utils.lua
lua/smart-splits/mux/wezterm.lua
lua/smart-splits/utils.lua

When using wsl in wezterm ( installed on windows ), the cursor does switch from wezterm to nvim, however it doesn't switch from nvim to wezterm.
As mentioned, the plugin is using wezterm cli for switching panes, however the command 'wezterm' is not recognized in WSL environment therefore the switching doesn't work.
Check if the environment is WSL and use the command 'wezterm.exe' instead of 'wezterm' ( note: this works only if the wezterm path on windows is set correctly on WSLENV ).

fix(mux): nvim-wezterm panes not seamlessly switching while using wsl2

---

lua/smart-splits/mux/init.lua

fixes #170 
---
In the future, there might room for further refactoring by collapsing the two consecutive `if` statements.
```diff
-  if multiplexer_moved or not will_wrap then
+  if multiplexer_moved or at_edge ~= AtEdgeBehavior.wrap then
return multiplexer_moved
end
```
This would also mean that `will_wrap` no longer needs to be passed to this function in the first place.

fix: never wrap unless at_edge is set to wrap

---

lua/smart-splits/api.lua

fix(api): move_cursor_previous is a no-op if previous win no longer exists

---

plugin/init.lua

Currently configuring the wezterm plugin with custom `direction_keys` will not work due to the hardcoded key-to-direction table. This PR fixes this issue by constructing the `direction_keys` table based on the configured keys instead.

fix: ensure that direction_keys can be configured

---

README.md
lua/smart-splits/api.lua
lua/smart-splits/config.lua
lua/smart-splits/types.lua

Implements https://github.com/mrjones2014/smart-splits.nvim/issues/201

feat(api): make floating window behavior configurable

---

kitty/neighboring_window.py
kitty/relative_resize.py

cause:
Due to the fact that after deleting pass_key.py, it didn't deal with the fact that kitty didn't send shortcuts to neovim when the environment was in neovim, resulting in not being able to do its own window operations inside neovim

fix(mux): Unable to use its own operations in neovim

---

kitty/neighboring_window.py
kitty/relative_resize.py
kitty/split_window.py

kitty.conf
**The shortcut here is passed to tmux**
```conf
map cmd+j kitten neighboring_window.py bottom cmd+j
map cmd+k kitten neighboring_window.py top    cmd+k
map cmd+h kitten neighboring_window.py left   cmd+h
map cmd+l kitten neighboring_window.py right  cmd+l
map --when-focus-on var:IS_NVIM cmd+j
map --when-focus-on var:IS_NVIM cmd+k
map --when-focus-on var:IS_NVIM cmd+h
map --when-focus-on var:IS_NVIM cmd+l
map ctrl+shift+j kitten relative_resize.py down  3 ctrl+shift+j 
map ctrl+shift+k kitten relative_resize.py up    3 ctrl+shift+k
map ctrl+shift+h kitten relative_resize.py left  3 ctrl+shift+h
map ctrl+shift+l kitten relative_resize.py right 3 ctrl+shift+l
map --when-focus-on var:IS_NVIM ctrl+shift+j
map --when-focus-on var:IS_NVIM ctrl+shift+k
map --when-focus-on var:IS_NVIM …
```

feat(mux): Use tmux inside kitty and compatible with window shortcuts

---

README.md

Fix the error in the example Wezterm: invalid KeyCode string Left, expected phys:CODE physical keycode string, got: phys:Left.

fix(docs): Fix the Wezterm plugin example keycodes

---

README.md

The title says it, Fixed not renderable [!NOTE] block in README.md due to missing LF.

fix: [!NOTE] Block

---

README.md
plugin/init.lua

Thanks for the great plugin 😄 
as per title this adds a `log_level` option for wezterm users with a default of `info` (as it currently is).
This allows turning off the logs in wezterm when calling `apply_to_config`, e.g:
```lua
smart_splits.apply_to_config(config, {
log_level = "warn",
})
```

feat(mux): wezterm supports log_level config

---

lua/smart-splits/config.lua

Should improve WSL support for users in lazy environments; if you don't call `.setup()` it should still work with this change.

fix(mux): Default WSL wezterm path at require time

---

lua/smart-splits/mux/tmux.lua

````
Error detected while processing VimSuspend Autocommands for "*":
Error executing lua callback: Vim:E475: Invalid value for argument cmd: 'tmux' is not executable
stack traceback:
[C]: in function 'jobstart'
...vim/lazy/smart-splits.nvim/lua/smart-splits/mux/tmux.lua:187: in function 'on_exit'
...im/lazy/smart-splits.nvim/lua/smart-splits/mux/utils.lua:74: in function <...im/lazy/smart-splits.nvim/lua/smart-splits/mux/utils.lua:73>
````

fix: Fix `on_exit` when nvim is running in a Flatpak package

---

lua/smart-splits/mux/init.lua

I am able to call `smart-splits::mux::split_pane` when using kitty as a backend so I think that sentence in the doc string on main is no longer the case. https://github.com/michaelfortunato/smart-splits.nvim/blob/793cd0c14cce113710939f2ede7a8cbf69bbadef/lua/smart-splits/mux/kitty.lua#L111
Thanks

fix(docs): kitty support for split_pane operation

---

README.md
smart-splits.tmux

This adds basic support for the Tmux package manager [TPM](https://github.com/tmux-plugins/tpm).
As an aside, I didn't implement support for jumping back to previously visited panes. I'm not really well versed in sh scripting like this, thats why I didn't feel comfortable handling configurable key-mappings properly with the Tmux versions.
Also, be aware that TPM executes all `*.tmux` files at the top level automatically. Just in case future releases should any such files to the repository.
See #247

feat(mux): add basic tpm support

---

README.md
lua/smart-splits/mux/zellij.lua

fix(mux): Restore cursor after zellij edge detection

---

plugin/init.lua

This is a typical situation if one is using tmux inside weterm. It could be possible to detect tmux by using `Pane:get_foreground_process_name()`, but it wouldn't work when using tmux in remote ssh connection (which is the main reason of this modification, since it's uncommon to run tmux inside wezterm locally)

fix(mux): Let wezterm pass keys if the active tab has only one pane

---

README.md

Following https://github.com/mrjones2014/smart-splits.nvim/pull/324, the `disable_multiplexer_nav_when_zoomed` config option is now usable with Kitty :)

docs: `disable_multiplexer_nav_when_zoomed` is usable with Kitty

---

plugin/init.lua

This was my approach for resolving #358.
An optional way of specifying modifiers is now:
```lua
smart_splits.apply_to_config(config, {
modifiers = {
-- NOTE:  This is the old way
-- move = "SUPER",
-- This "breaks" in neovim since `<C-l>` and `<C-L>` are
-- indistinguishable
-- resize = "CTRL|SHIFT",
move = {
wezterm = "SUPER",
neovim = "ALT",
},
resize = {
wezterm = "CTRL|SHIFT",
neovim = "CTRL|ALT",
},
},
})
```
This will insert the `move.wezterm` and `resize.wezterm` key mappings into
`config.keymaps`.  When passing the keys through to `neovim` via
`action.SendKey`, it will override the `mods` with whatever is provided under
`move.neovim` and `resize.neovim`.
It checks if these values are `table`s and so should not be a breaking change.
This lets me remove all my custom config for …

feat(mux): support wezterm mapping
