lua/smart-splits/init.lua

Fixes #11 
That one was a _**wild**_ ride to figure out, so in the process I also refactored basically the whole damn plugin basically.
The logic is a lot more clear and concise now, much less spaghetti code.

fix some wild edge cases with complex layouts

---

lua/smart-splits/api.lua

believe these were left in by mistake while figuring out some difficult edge cases

remove print statements from api.lua

---

README.md
lua/smart-splits/api.lua
lua/smart-splits/config.lua
lua/smart-splits/tmux.lua

Adds a tmux integration like Navigator.nvim.

add tmux integration

---

lua/smart-splits/api.lua
lua/smart-splits/tmux.lua

Check if there is a tmux session before trying to use it

---

README.md
lua/smart-splits/api.lua
lua/smart-splits/config.lua
lua/smart-splits/resize-mode.lua

add configurable default_amount and make resize mode keymaps accept a range

---

README.md
lua/smart-splits/api.lua
lua/smart-splits/config.lua

add config option to disable edge wrapping

---

README.md
lua/smart-splits/api.lua

improved(mappings): support ranges in keymaps (for example, `10<A-h>` to `resize_left` by `(10 * config.default_amount)`)

---

README.md
lua/smart-splits/config.lua

chore(docs): Update README.md to reflect how multiplexer is chosen correctly

---

.github/ISSUE_TEMPLATE/bug-report.yml

chore: Add additional data to the GitHub issue form

---

README.md
lua/smart-splits/mux/tmux.lua
lua/smart-splits/mux/wezterm.lua

fix(mux): Cannot move across mux panes when `wrap_at_edge` and both panes are running `nvim`

---

lua/smart-splits/api.lua

feat(api): `at_edge = 'split'` will behave like `at_edge = 'stop'` in ignored buffers when no mux window to move to

---

lua/smart-splits/mux/wezterm.lua

feat(mux): Resize Wezterm panes when only single Neovim split is open

---

README.md
lua/smart-splits/mux/init.lua
lua/smart-splits/mux/kitty.lua
lua/smart-splits/mux/tmux.lua
lua/smart-splits/mux/wezterm.lua
lua/smart-splits/types.lua

feat(mux): Add API to create mux splits via smart-splits.nvim

---

README.md
lua/smart-splits/commands.lua
lua/smart-splits/config.lua
lua/smart-splits/log/async.lua
lua/smart-splits/log/file.lua
lua/smart-splits/log/init.lua
lua/smart-splits/mux/init.lua
lua/smart-splits/mux/kitty.lua
lua/smart-splits/resize-mode.lua

feat(api): Add asynchronous logging

---

README.md

chore(docs): Add mux SSH support notice to docs

---

plugin/smart-splits.vim

fix(mux): Correctly set Wezterm user var more consistently in more scenarios

---

lua/smart-splits/api.lua
lua/smart-splits/utils.lua

feat(api): return to previous win if current win is floating

---

lua/smart-splits/config.lua

feat(mux): Automatically disable mux integration if running in a GUI

---

lua/smart-splits/config.lua
lua/smart-splits/mux/wezterm.lua
lua/smart-splits/utils.lua
plugin/smart-splits.vim

fix(mux): Always set wezterm user vars in wezterm

---

lua/smart-splits/config.lua
lua/smart-splits/utils.lua

fix(mux): Don't set up Wezterm mux if running in GUI

---

lua/smart-splits/mux/tmux.lua
lua/smart-splits/mux/utils.lua

fix(mux): Change `on_exit` to run on `VimLeavePre` instead of `VimLeave`

---

lua/smart-splits/api.lua

feat: support count in move commands

---

README.md

It was a pain for me to figure out, so I guess might be useful to some

docs: add example how to disable wrapping in tmux

---

lua/smart-splits/resize-mode.lua

fix(api): Restore previous mappings on exit from resize mode

---

kitty/neighboring_window.py
kitty/split_window.py

Causes:
I'm sorry, I confused my local environment with the git public directory, which resulted in commits that were missing parts of the code.
The only feature currently affected is window cutting, sorry about that!

fix: 'encode_key_mapping' is not defined

---

plugin/init.lua

Added a `default_amount` option to configure the resize delta in wezterm.

feat(mux): Configurable resize delta in Wezterm plugin

---

README.md
plugin/init.lua

feat(mux): Update Wezterm plugin to support separate direction keys for move vs. resize actions

---

lua/smart-splits/mux/tmux.lua

fix(mux): get tmux pane running vim instead of active pane

---

lua/smart-splits/api.lua

Fixes #245 
Does not account for folds state, I don't know of a way to do that.

feat(api): Swap buffer view state when swapping wins with the same buf

---

README.md
lua/smart-splits/config.lua

feat(mux): Allow mux to be set via `vim.g.smart_splits_multiplexer_integration`

---

README.md
smart-splits.tmux

I forgot to add this with my last PR for the TPM.
closes #247

feat(mux): make step-size for resizing configurable with TPM

---

README.md
lua/smart-splits/config.lua
lua/smart-splits/mux/zellij.lua
lua/smart-splits/types.lua

Adds experimental Zellij support.
Relates to #111

feat(mux): Experimental Zellij support

---

README.md
lua/smart-splits/mux/zellij.lua

chore(mux): Update docs

---

README.md

feat(mux): Promote Zellij integration to officially supported

---

lua/smart-splits/mux/kitty.lua

The "zoomed pane" is a "stack window" in kitty (ref: https://sw.kovidgoyal.net/kitty/layouts/#the-stack-layout).

fix: Add zoomed pane detection for kitty

---

README.md
lua/smart-splits/config.lua
lua/smart-splits/mux/zellij.lua

Fixes #326 
@rafaelpirolla can you test this out? I wasn't sure if we need to change _all_ the actions or just the one in this commit.

feat(mux): Allow Zellij to move to next tab

---

lua/smart-splits/mux/init.lua

fix: Cache mux.get() evaluation for performance

---

lua/smart-splits/api.lua

fix: abort if full height and no mux

---

lua/smart-splits/utils.lua

fix: add special handling for Snacks.explorer window
